# Generated by Django 3.0.14 on 2022-09-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_remove_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passed',
            field=models.ManyToManyField(to='academy.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='academy.Course'),
        ),
    ]
