# Generated by Django 3.0.14 on 2022-09-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20220909_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passed',
            field=models.ManyToManyField(null=True, to='academy.Course'),
        ),
    ]
