# Generated by Django 3.0.14 on 2022-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_auto_20220909_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='academy.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passed',
            field=models.ManyToManyField(blank=True, to='academy.Course'),
        ),
    ]
