# Generated by Django 3.0.14 on 2022-09-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_auto_20220909_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passed',
        ),
    ]
