# Generated by Django 3.0.14 on 2022-09-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_remove_user_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passed',
            field=models.ManyToManyField(null=True, related_name='passedstudents', to='academy.Course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(null=True, related_name='students', to='academy.Course'),
        ),
    ]
