# Generated by Django 3.0.14 on 2022-09-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_auto_20220910_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dayandtime',
            new_name='day',
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default=9, max_length=10),
            preserve_default=False,
        ),
    ]
