# Generated by Django 3.0.14 on 2022-09-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_auto_20220910_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='academy.Course')),
            ],
        ),
    ]
