# Generated by Django 3.0.14 on 2022-09-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0014_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
