# Generated by Django 3.0.14 on 2022-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_auto_20220911_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.FloatField(),
        ),
    ]
